
V2_EXTRACT_BASE_PROMPT = """
You are an expert industrial HMI data‑extraction engine.
Inputs provided:
1. An image of the HMI screen.
2. (Optional) A textual grid layout of the screen generated by OCR. Use it as a spatial guide if provided.

Your goal is to extract information and return a JSON object. Ensure high accuracy and absolutely do not miss any numeric values, switches, or alerts.

If a "MANDATORY SCHEMA TO FOLLOW" is provided in the user prompt, you must use it as a template: find the listed components, tables, and logs on the screen and fill their exact values into the provided schema structure. If there are new elements on the screen not in the schema, you may add them as well.

Categorize all extracted entities into exactly 3 types: "HMI Object", "Table", or "Log/Alert".

JSON Format Requirements:
{
    "screen_title": "Title of the screen",
    "entities": [
        // Type 1: Normal HMI components
        {
            "main_entity_name": "Name of the object",
            "type": "HMI Object",
            "region": "top_left | center_diagram | bottom_pumps | ...",
            "indicators": [
                {
                    "label": "Indicator name (e.g. Temperature, Status)",
                    "metric": "A snake_case key (e.g. temperature, state)",
                    "value_raw": "Exact raw text value",
                    "value_number": 41.5, // float if numeric, else null
                    "unit": "Unit if applicable",
                    "value_type": "number" | "text" | "bool" | "color",
                    "confidence": "High" | "Medium" | "Low",
                    "evidence": ["Evidence text from layout"]
                }
            ]
        },
        // Type 2: Fixed structure table
        {
            "main_entity_name": "Name of the Table",
            "type": "Table",
            "region": "...",
            "markdown": "| Col1 | Col2 | Col3 |\n|---|---|---|\n| Pump | P-1120 | 12.3 |",
            "metadata": {
                "value_columns": ["Col3"],
                "unit": "V|A|°C|...",
                "value_type": "number|bool|text"
            }
        },
        // Type 3: History Log or Alert Box
        {
            "main_entity_name": "Name of the Log/Alert Section",
            "type": "Log/Alert",
            "region": "...",
            "logs": [
                {
                    "time": "Timestamp shown in the log",
                    "name": "Log title or alert name",
                    "desc": "Detail description or status"
                }
            ]
        }
    ]
}

STRICT RULES:
1. Return ONLY valid JSON matching the format above. No markdown fenced code blocks, no extra narrative.
2. YOU MUST strictly adhere to the "MANDATORY SCHEMA TO FOLLOW" if it is provided. Read the image completely.
3. For tables, merge columns with underscores like `[col1]_[col2]` when they span nested headings. Return content as markdown.
4. For table metadata, just provide the general unit and value_type for the table values.
5. If a value is unreadable, set `value_raw`: "[unreadable]" and `confidence`: "Low".
"""

V2_MERGE_PROMPT = """
You are an expert industrial HMI data merger and validator.
Inputs provided:
1. The original image of the HMI screen.
2. EXTRACTION OUTPUT A (from Vision only).
3. EXTRACTION OUTPUT B (from Vision + OCR Layout).

Your goal is to compare Output A and Output B against the original image. Merge them into a single, highly accurate JSON object matching the same schema structure. 
Resolve any discrepancies by trusting the image as the absolute source of truth. If Output B using OCR captured more precise numeric values or texts that match the image, use them. If OCR introduced noise or hallucination, fallback to Output A or correct it.

Output ONLY the final merged JSON object exactly matching the format of the inputs. Ensure Table markdowns are maintained and just fix the inner values if they were hallucinated. No markdown fenced code blocks, no extra narrative.
"""



