services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: kvm-ocr-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "33030:8000"
    networks:
      - mynet

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    container_name: kvm-ocr-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "33031:3000"
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:
    external: true
